language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: vx1IOKkBvmk3X2iR8etOI330Ze6E/RbodM6Ksid3dVE9GBH9aqJrj7zubUU1Tiw5koW61PMmjJL1GtFeLItGG/nX4Gi8D0YZmRV22lH7IxqFEooRx4uGU/FbW3xlCjHBQS7c1LDezO+dz0qcXlSzlxjsXm5H1LU0I2nq6gHjWTkJSG89XDHJaPAZfxKRnzC+5P9njTfOdDUZnAsIQQVPhDLZA4pyjOJWJKF32sc+59ey1yWzNvhJvqgAnBcRJJm/2RGYpUWIbAv9kOWbnu0iLC3OIzNPMybb2aoRsTCb5SJBNt+LRLp10g/KZZlTeu9wfcAs3J+mShkBR3F7hd9n/z8WlkzCiZeFEPNtHEe0Soy6VgntvqAOBGp2Zh6UVz5QLniaXf9w4uNhBGLZN9Gg3mAdlDM5KpDD0jvTA9wNGnIb8JDlQujNWft6sbRMFbFySMQ9orBxlnpUmM6TxKN2hKuBOPe7Htw523oJAoThOKXi00oXEkYii+WFUdYDQySnXwsNV38py4Y1moCgFy8EGBgl+oqsVfYwzqIfqsP/gs3X8EBqIM+ydiD4PUPMXsqJiNHBGQeAz5AMiYIRBTy8P1z5xQNqdyGe96sTyLshecmresWObGw2ZS+MRfC12NcADCglN7NT1zEZlbNyeK30iuNwOIRpfBjjg7lVA9AJ3nc=
  app: still-ravine-27189
  on:
    repo: Ray-Yeung/node-shopping-list-integration-tests
